version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.jetbrains.kotlin:kotlin-stdlib"
        versions: ["1.5.x"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
